from pathlib import Path
from collections import defaultdict
import pandas as pd
import numpy as np

from normalize import normalize_text


# ============================================================
# CONFIG
# ============================================================

BASE = Path(__file__).resolve().parents[1]

TRAIN_DIR = BASE / "dataset" / "train"

S1_PATH = TRAIN_DIR / "train_source1.tsv"
S2_PATH = TRAIN_DIR / "train_source2.tsv"
S3_PATH = TRAIN_DIR / "train_source3.tsv"

SAMPLE_S1 = 5000
CHUNK_SIZE = 200_000


# ============================================================
# BLOCKING KEY FUNCTIONS
# ============================================================

def get_tokens(text):

    text = normalize_text(text)

    if not text:
        return []

    return text.split()


def get_keys(row):

    country = str(row["country"])

    name = normalize_text(row["business_name"])
    address = normalize_text(row["business_address"])

    name_tokens = get_tokens(name)
    address_tokens = get_tokens(address)

    compact_name = name.replace(" ", "")
    compact_address = address.replace(" ", "")

    first_name = (
        name_tokens[0]
        if name_tokens
        else ""
    )

    first_address = (
        address_tokens[0]
        if address_tokens
        else ""
    )

    return {
        "country_name_first": (
            country,
            first_name
        ),

        "country_name_prefix3": (
            country,
            compact_name[:3]
        ),

        "country_name_token_prefix3": (
            country,
            first_name[:3]
        ),

        "country_address_first": (
            country,
            first_address
        ),

        "country_address_prefix3": (
            country,
            compact_address[:3]
        ),
    }


BLOCK_NAMES = [
    "country_name_first",
    "country_name_prefix3",
    "country_name_token_prefix3",
    "country_address_first",
    "country_address_prefix3",
]


# ============================================================
# STEP 1: SAMPLE SOURCE 1
# ============================================================

print("=" * 70)
print("STEP 1: Loading Source-1 sample")
print("=" * 70)

s1 = pd.read_csv(
    S1_PATH,
    sep="\t",
    dtype=str,
    nrows=SAMPLE_S1
)

print(f"Source-1 records: {len(s1)}")


# ============================================================
# STEP 2: BUILD QUERY KEYS
# ============================================================

print("\n" + "=" * 70)
print("STEP 2: Building Source-1 blocking keys")
print("=" * 70)

# For each block:
#     block_key -> number of S1 records using that key

s1_key_frequency = {
    block: defaultdict(int)
    for block in BLOCK_NAMES
}

for _, row in s1.iterrows():

    keys = get_keys(row)

    for block in BLOCK_NAMES:

        key = keys[block]

        # Don't use empty blocking values
        if key[1] != "":
            s1_key_frequency[block][key] += 1


for block in BLOCK_NAMES:

    print(
        f"{block:35s}"
        f"unique_keys={len(s1_key_frequency[block]):8d}"
    )


# ============================================================
# STEP 3: STREAM SOURCE AND COUNT MATCHING RECORDS
# ============================================================

def analyze_source(file_path, source_name):

    print("\n" + "=" * 70)
    print(f"STEP 3: Analyzing {source_name}")
    print("=" * 70)

    # For every S1:
    # number of candidates generated by each block.
    #
    # Since multiple S1 records can share a block key,
    # we distribute the candidate count to each S1
    # using that key.

    candidate_counts = {
        block: defaultdict(int)
        for block in BLOCK_NAMES
    }

    total_records = 0

    for chunk_number, chunk in enumerate(
        pd.read_csv(
            file_path,
            sep="\t",
            dtype=str,
            chunksize=CHUNK_SIZE
        ),
        start=1
    ):

        total_records += len(chunk)

        for _, row in chunk.iterrows():

            keys = get_keys(row)

            for block in BLOCK_NAMES:

                key = keys[block]

                if key[1] == "":
                    continue

                number_of_s1 = (
                    s1_key_frequency[block]
                    .get(key, 0)
                )

                if number_of_s1 == 0:
                    continue

                # This Source-2/3 record is a candidate
                # for every S1 sharing this block key.
                #
                # We cannot identify each S1 here without
                # storing another large structure, so we keep
                # aggregate candidate-pair volume.

                candidate_counts[block]["total"] += (
                    number_of_s1
                )

        print(
            f"Processed chunk {chunk_number} "
            f"({total_records:,} records)"
        )

    print(
        f"\nTotal {source_name} records scanned: "
        f"{total_records:,}"
    )

    print("\nCandidate pairs generated by each block:")

    for block in BLOCK_NAMES:

        count = candidate_counts[block]["total"]

        average = count / len(s1)

        print(
            f"{block:35s}"
            f"pairs={count:15,} "
            f"avg_per_s1={average:12.2f}"
        )

    return candidate_counts


# ============================================================
# STEP 4: ANALYZE S2
# ============================================================

s2_counts = analyze_source(
    S2_PATH,
    "Source 2"
)


# ============================================================
# STEP 5: ANALYZE S3
# ============================================================

s3_counts = analyze_source(
    S3_PATH,
    "Source 3"
)


# ============================================================
# STEP 6: SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("BLOCKING CANDIDATE VOLUME SUMMARY")
print("=" * 70)

print("\nSource 2:")

for block in BLOCK_NAMES:

    count = s2_counts[block]["total"]

    print(
        f"{block:35s}"
        f"{count / len(s1):12.2f} candidates/S1"
    )


print("\nSource 3:")

for block in BLOCK_NAMES:

    count = s3_counts[block]["total"]

    print(
        f"{block:35s}"
        f"{count / len(s1):12.2f} candidates/S1"
    )


print("\n" + "=" * 70)
print("CANDIDATE VOLUME ANALYSIS COMPLETE")
print("=" * 70)